# Pytorch Tidbits

Small torch functions that might come handy later

In [1]:
import torch
import torchvision
import numpy as np
import matplotlib.pyplot as plt

In [8]:
# torch.unsqueeze(input, dim) -> tensor

# Returns a new tensor with a dimension of size on inserted at the specific position

filler = torch.FloatTensor([100, 200, 200])
# filler = torch.FloatTensor(filler)
#filler.unsqueeze(1)

filler.unsqueeze(1).unsqueeze(1)

tensor([[[100.]],

        [[200.]],

        [[200.]]])

In [21]:
boxes = torch.FloatTensor([[45, 50, 65, 70],
                     [95, 105, 120, 135]])

left = 10
top = 100


In [18]:
new_boxes = boxes + torch.FloatTensor([left, top, left, top]).unsqueeze(0)
    

In [19]:
new_boxes

tensor([[ 55., 150.,  75., 170.],
        [105., 205., 130., 235.]])

In [22]:
boxes

tensor([[ 45.,  50.,  65.,  70.],
        [ 95., 105., 120., 135.]])

To find the centers of the bounding boxes' labels, we take all the boxes tensors and slice the first two elements:

In [24]:
boxes[:, :2]

tensor([[ 45.,  50.],
        [ 95., 105.]])

In [2]:
def safe_softmax(probs, dim=None):
    exp = torch.exp(probs - torch.max(probs, dim=dim, keepdim=True)[0])
    return exp / torch.sum(exp, dim=dim, keepdim=True)


In [5]:
probs = torch.tensor([0.8, 0.95, 0.20, 0.4, 0.3])

exp = torch.exp(probs - torch.max(probs, dim=-1, keepdim=True)[0])

In [8]:
ex_p = probs - torch.max(probs, dim=-1, keepdim=True)[0]

In [9]:
ex_p

tensor([-0.1500,  0.0000, -0.7500, -0.5500, -0.6500])

In [10]:
torch.exp(ex_p)

tensor([0.8607, 1.0000, 0.4724, 0.5769, 0.5220])

In [12]:
final =exp / torch.sum(exp, dim=-1, keepdim=True)
final

tensor([0.2508, 0.2914, 0.1376, 0.1681, 0.1521])

In [14]:
pred = [23, 2, 34, 12, 34, 212,10]

pred_deltas = pred[1:]

In [15]:
pred_deltas

[2, 34, 12, 34, 212, 10]