# Pytorch Tidbits

Small torch functions that might come handy later

In [1]:
import torch
import torchvision
import numpy as np
import matplotlib.pyplot as plt

In [8]:
# torch.unsqueeze(input, dim) -> tensor

# Returns a new tensor with a dimension of size on inserted at the specific position

filler = torch.FloatTensor([100, 200, 200])
# filler = torch.FloatTensor(filler)
#filler.unsqueeze(1)

filler.unsqueeze(1).unsqueeze(1)

tensor([[[100.]],

        [[200.]],

        [[200.]]])

In [21]:
boxes = torch.FloatTensor([[45, 50, 65, 70],
                     [95, 105, 120, 135]])

left = 10
top = 100


In [18]:
new_boxes = boxes + torch.FloatTensor([left, top, left, top]).unsqueeze(0)
    

In [19]:
new_boxes

tensor([[ 55., 150.,  75., 170.],
        [105., 205., 130., 235.]])

In [22]:
boxes

tensor([[ 45.,  50.,  65.,  70.],
        [ 95., 105., 120., 135.]])

To find the centers of the bounding boxes' labels, we take all the boxes tensors and slice the first two elements:

In [24]:
boxes[:, :2]

tensor([[ 45.,  50.],
        [ 95., 105.]])

In [2]:
def safe_softmax(probs, dim=None):
    exp = torch.exp(probs - torch.max(probs, dim=dim, keepdim=True)[0])
    return exp / torch.sum(exp, dim=dim, keepdim=True)


In [5]:
probs = torch.tensor([0.8, 0.95, 0.20, 0.4, 0.3])

exp = torch.exp(probs - torch.max(probs, dim=-1, keepdim=True)[0])

In [8]:
ex_p = probs - torch.max(probs, dim=-1, keepdim=True)[0]

In [9]:
ex_p

tensor([-0.1500,  0.0000, -0.7500, -0.5500, -0.6500])

In [10]:
torch.exp(ex_p)

tensor([0.8607, 1.0000, 0.4724, 0.5769, 0.5220])

In [12]:
final =exp / torch.sum(exp, dim=-1, keepdim=True)
final

tensor([0.2508, 0.2914, 0.1376, 0.1681, 0.1521])

In [14]:
pred = [23, 2, 34, 12, 34, 212,10]

pred_deltas = pred[1:]

In [15]:
pred_deltas

[2, 34, 12, 34, 212, 10]

# loading files 

In [ ]:
# when loading files with 
# readlines()
# to strip the \n from the end of the lines


sample_ids = tuple(x.strip() for x in sample_ids)

In [88]:
arr = [
  [8, [4]], 
  [[90, 91], -1, 3], 
  [9, 62], 
  [[-7, -1, [-56, [-6]]]], 
  [201], 
  [[76, 0], 18],
]

In [91]:
def nested_arr(arr):
    result = 0
    for item in arr:
        result += min(item)
        print(result)

In [79]:
def nested_arr(arr):
    nested_arr = []
    for i in range(len(arr)):
        if len(arr[i]) == 1:
            nested_arr.append(arr[i])
        elif len(arr[i]) > 1:
                if isinstance(arr[i], list):
                    nested_arr.append(min(arr[i]))
                    
    return nested_arr

In [84]:
for x in arr:
    print(x)

[8, [4]]
[[90, 91], -1, 3]
[9, 62]
[[-7, -1, [-56, [-6]]]]
[201]
[[76, 0], 18]


In [87]:
new_arr = []
for x in range(len(arr)):
    for i in range(len(arr[x])):
        current = i
        smallest_index = i

        for j in range(i+1, len(arr)):
            if arr[smallest_index] > arr[j]:
                smallest_index = j
                new_arr.append(smallest_index)
                print((new_arr))

TypeError: '>' not supported between instances of 'int' and 'list'

In [72]:
nested_arr(arr)

TypeError: '<' not supported between instances of 'list' and 'int'

In [68]:
for i in range(len(arr)):
    if len(arr[i]) == 1:
        new_arr.append(arr[i])
        for j in range(len(arr[i])):
            new_arr.append(min(j))
            print(sum(new_arr))


TypeError: 'int' object is not iterable

In [ ]:
new_arr = []

for i in range(len(arr)):
    if arr[0] == None:
        break
    
    arr[i][i] == 

In [52]:
def nested_arr(L):
    total = 0
    for i in L:
        if isinstance(i, L):
            total += nested_arr(i)
        else:
            total+=i
    return total

In [56]:
def my_max_by_weight(sequence):
    if not sequence:
        raise ValueError('empty sequence')

    maximum = sequence[0]

    for item in sequence:
        # Compare elements by their weight stored
        # in their second element.
        if item[1] > maximum[1]:
            maximum = item

    return maximum