## Tensors Experimentation

In [44]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

RuntimeError: output with backend CPU and dtype Float doesn't match the desired backend CPU and dtype Double

In [44]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

RuntimeError: output with backend CPU and dtype Float doesn't match the desired backend CPU and dtype Double

In [41]:
x = x.new_ones(5, 3, dtype=torch.double)


In [39]:
y = torch.rand(5, 3, dtype=torch.double)
print(y)

tensor([[0.4092, 0.8645, 0.8849],
        [0.5033, 0.3086, 0.9250],
        [0.3419, 0.5535, 0.2600],
        [0.2569, 0.6819, 0.3482],
        [0.8642, 0.4868, 0.7712]], dtype=torch.float64)


In [30]:
x = torch.tensor([5, 3])
print(x)

tensor([5, 3])


In [25]:
x = torch.zeros(5, 4, dtype=torch.long)

print(x)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])


In [24]:
x = torch.zeros(5, 4)
print(x)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
